// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// If env vars are missing (common on first Netlify deploy), we keep the app usable offline.
export const isSupabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) &&
  !SUPABASE_URL?.includes('placeholder') &&
  !SUPABASE_PUBLISHABLE_KEY?.includes('placeholder');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a safe client. When not configured, we expose a proxy so imports don't crash.
export const supabase: any = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  })
  : new Proxy(
    {},
    {
      get() {
        return () => {
          throw new Error(
            'Supabase no está configurado. Añade VITE_SUPABASE_URL y VITE_SUPABASE_PUBLISHABLE_KEY en Netlify para activar lo online.'
          );
        };
      },
    }
  );